/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-09-20 11:02:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class aboutus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("   <meta charset=\"UTF-8\">\r\n");
      out.write("   <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("   <title>AboutUs</title>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"styles/aboutus.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Link -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("    <!-- Bootstrap Link -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Font Awesome Cdn -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css\">\r\n");
      out.write("    <!-- Font Awesome Cdn -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <style>\r\n");
      out.write("  .custom-button {\r\n");
      out.write("    background-color: orange;\r\n");
      out.write("    border: none;\r\n");
      out.write("    color: black;\r\n");
      out.write("     font-weight: bold;\r\n");
      out.write("    transition: color 0.3s ease;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .custom-button:hover {\r\n");
      out.write("    color: white;\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   \r\n");
      out.write("<!-- Navbar Start -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg\" id=\"navbar\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"index.html\" id=\"logo\"><span>Parts</span>Universe</a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#mynavbar\">\r\n");
      out.write("            <span><i class=\"fa-solid fa-bars\"></i></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"mynavbar\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" id=\"home-link\" href=\"index.jsp\">Home</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" id=\"login-link\" href=\"login.jsp\">Login</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" id=\"signup-link\" href=\"sinup.jsp\">Signup</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" id=\"profile-link\" href=\"useraccount.jsp\">Profile</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" id=\"packages-link\" href=\"aboutus.jsp\">AboutUs</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" id=\"services-link\" href=\"faq.JSP\">FAQ</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" id=\"gallary-link\" href=\"privacy.jsp\">Privacy Policy</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" id=\"about-link\" href=\"contact.jsp\">Contact Us</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" id=\"about-link\" href=\"terms.jsp\">T&C</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Navbar End -->\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("        <h1 style = \"font-size:80px;\">About Us</h1>\r\n");
      out.write("        <p style = \"font-size:20px; color:gray; font-wight:bold;\">Your Trusted Partner in Parts Universe,Learn About Us</p>\r\n");
      out.write("             <div class=\"content-box\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <i class=\"bx bx-bar-chart-alt bx-md\"></i>\r\n");
      out.write("                    <h2 style = \"font-size:30px;\">Our Mission</h2>\r\n");
      out.write("                  <p>At Parts Universe, our mission is to provide high-quality, reliable vehicle spare parts to keep your vehicle running smoothly. We are dedicated to offering a vast selection of parts and accessories that meet the highest standards of performance and durability.</p>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <i class=\"bx bx-laptop bx-md\"></i>\r\n");
      out.write("                    <h2 style = \"font-size:30px;\">What We Do</h2>\r\n");
      out.write("                   <p>We specialize in offering a comprehensive range of vehicle spare parts, from engine components to electrical systems and everything in between. Whether you’re a professional mechanic or a DIY enthusiast, we have the right parts and accessories to meet your needs. Our extensive inventory and \r\n");
      out.write("                   commitment to quality ensure that you get the best products for your vehicle.</p>\r\n");
      out.write("                         \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <i class='bx bx-user bx-md'></i>\r\n");
      out.write("\r\n");
      out.write("                    <h2 style = \"font-size:30px;\">Our Values</h2>\r\n");
      out.write("                <p>Quality Assurance: We source our parts from reputable manufacturers and conduct rigorous quality checks to ensure reliability and performance.\r\n");
      out.write("				Customer Focus: Our priority is to understand and meet the needs of our customers, providing personalized support and expert advice.</p>\r\n");
      out.write("                         \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <i class=\"bx bx-mail-send bx-md\"></i>\r\n");
      out.write("                    <h2 style = \"font-size:30px;\">Our Team</h2>\r\n");
      out.write("                    <p> Our team consists of automotive professionals with extensive experience in the industry. From knowledgeable customer service representatives to skilled logistics staff, we work together to provide an exceptional experience for our customers.</p>\r\n");
      out.write("                         \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <i class=\"bx bx-bar-chart-alt bx-md\"></i>\r\n");
      out.write("                    <h2 style = \"font-size:30px;\">Looking Ahead</h2>\r\n");
      out.write("                    <p>As we continue to grow, we remain committed to expanding our product offerings and enhancing our services. We aim to be your go-to source for all your vehicle spare parts needs, delivering excellence in every transaction.</p>\r\n");
      out.write("                         \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <i class=\"bx bx-paint bx-md\"></i>\r\n");
      out.write("                    <h2 style = \"font-size:30px;\">Our Commitment</h2>\r\n");
      out.write("                    <p> Looking ahead, we are focused on expanding our product range and continuously improving our services. We are committed to staying at the cutting edge of the automotive parts industry to better serve our customers and meet their evolving needs.</p>\r\n");
      out.write("                         \r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
