/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-10-13 16:51:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1728837845958L));
    _jspx_dependants.put("jar:file:/C:/Users/acer/Desktop/Online%20Vehicle%20Spare%20Parts%20System/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/OnlineSparePartsSystem/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602854172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Parts Universe</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles/index.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Link -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("    <!-- Bootstrap Link -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Font Awesome Cdn -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css\">\r\n");
      out.write("    <!-- Font Awesome Cdn -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <style>\r\n");
      out.write("    *{\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    scroll-behavior: smooth;\r\n");
      out.write("    font-family: 'Lato', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("#navbar {\r\n");
      out.write("  background-color: #343a40;\r\n");
      out.write("  padding: 15px 0;\r\n");
      out.write("  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav .nav-link {\r\n");
      out.write("  color: #000000; /* Black text color */\r\n");
      out.write("  margin-right: 15px;\r\n");
      out.write("  font-weight: 500;\r\n");
      out.write("  transition: color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav .nav-link:hover,\r\n");
      out.write(".navbar-nav .nav-link.active {\r\n");
      out.write("  color: #ffc107; /* Yellow color on hover or when active */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#logo {\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  font-size: 24px;\r\n");
      out.write("  font-weight: 700;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logo span {\r\n");
      out.write("  color: #ffc107;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary {\r\n");
      out.write("  background-color: #ffc107; /* Button background color */\r\n");
      out.write("  border: none; /* Remove border */\r\n");
      out.write("  color: #000000; /* Black text color */\r\n");
      out.write("  font-weight: 600; /* Bold text */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary:hover {\r\n");
      out.write("  background-color: #e0a800; /* Darker yellow on hover */\r\n");
      out.write("  color: #ffffff; /* White text color on hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".navbar-toggler {\r\n");
      out.write("  border-color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-toggler-icon {\r\n");
      out.write("  background-image: url(\"data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='%23ffffff' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E\");\r\n");
      out.write("  /* White lines for the toggle icon */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".navbar {\r\n");
      out.write("  min-height: 60px;\r\n");
      out.write("}\r\n");
      out.write("/* Home Section Start */\r\n");
      out.write(".home{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 90vh;\r\n");
      out.write("    background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.2)), url(images/background.jpeg);\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("}\r\n");
      out.write(".home .content{\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding-top: 200px;\r\n");
      out.write("}\r\n");
      out.write(".home .content h5{\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-size: 38px;\r\n");
      out.write("    font-weight: 550;\r\n");
      out.write("    text-shadow: 0px 1px 1px black;\r\n");
      out.write("}\r\n");
      out.write(".home .content h1{\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-size: 70px;\r\n");
      out.write("    font-weight: 550;\r\n");
      out.write("    text-shadow: 0px 1px 1px black;\r\n");
      out.write("    margin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write(".changecontent::after{\r\n");
      out.write("    content: ' ';\r\n");
      out.write("    color: #ffa500;\r\n");
      out.write("    text-shadow: 0px 1px 1px black;\r\n");
      out.write("    animation: changetext 10s infinite linear;\r\n");
      out.write("}\r\n");
      out.write(" .custom-button {\r\n");
      out.write("    background-color: orange;\r\n");
      out.write("    border: none;\r\n");
      out.write("    color: black;\r\n");
      out.write("     font-weight: bold;\r\n");
      out.write("    transition: color 0.3s ease;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .custom-button:hover {\r\n");
      out.write("    color: white;\r\n");
      out.write("  }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Navbar Start -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg\" id=\"navbar\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"index.html\" id=\"logo\"><span>Parts</span>Universe</a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#mynavbar\">\r\n");
      out.write("            <span><i class=\"fa-solid fa-bars\"></i></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"mynavbar\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" id=\"home-link\" href=\"index.jsp\">Home</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" id=\"login-link\" href=\"login.jsp\">Login</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" id=\"signup-link\" href=\"sinup.jsp\">Signup</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" id=\"profile-link\" href=\"useraccount.jsp\">Profile</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" id=\"packages-link\" href=\"aboutus.jsp\">AboutUs</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" id=\"services-link\" href=\"faq.JSP\">FAQ</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" id=\"gallary-link\" href=\"privacy.jsp\">Privacy Policy</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" id=\"about-link\" href=\"contact.jsp\">Contact Us</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" id=\"about-link\" href=\"terms.jsp\">T&C</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <form class=\"d-flex\" id=\"searchForm\" onsubmit=\"return performSearch()\">\r\n");
      out.write("    			<input class=\"form-control me-2\" type=\"text\" id=\"query\" placeholder=\"Search\">\r\n");
      out.write("    			<button class=\"btn custom-button\" type=\"submit\">Search</button>\r\n");
      out.write("			</form>\r\n");
      out.write("	            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Navbar End -->\r\n");
      out.write("    <!-- Home Section Start -->\r\n");
      out.write("    <div class=\"home\">\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <h5>Welcome To Parts Universe</h5>\r\n");
      out.write("            <h1>Discover <span class=\"changecontent\"></span></h1>\r\n");
      out.write("            <p>Experience Unmatched Performance with our Superior Replacement Parts!</p>\r\n");
      out.write("            <a href=\"#book\">OBSERVE</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Home Section End -->\r\n");
      out.write("    <!-- Section Packages Start -->\r\n");
      out.write("    <section class=\"packages\" id=\"packages\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"main-txt\">\r\n");
      out.write("          <h1><span>Brand</span>Categories</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\" style=\"margin-top: 30px;\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-4 py-3 py-md-0\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <img src=\"./images/bmw.jpeg\" width=\"200\" height=\"200\" alt=\"\">\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3>BMW</h3>\r\n");
      out.write("                <p>Genuine Parts for Optimal Performance of Your BMW!</p>\r\n");
      out.write("                <div class=\"star\">\r\n");
      out.write("                  <i class=\"fa-solid fa-star checked\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star checked\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star checked\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star \"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star \"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("               \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 py-3 py-md-0\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <img src=\"./images/benz.jpeg\" width=\"200\" height=\"200\" alt=\"\">\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3>Benz</h3>\r\n");
      out.write("                <p>Genuine Parts for Optimal Performance of Your Benz!</p>\r\n");
      out.write("                <div class=\"star\">\r\n");
      out.write("                  <i class=\"fa-solid fa-star checked\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star checked\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star checked\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star \"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star \"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 py-3 py-md-0\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <img src=\"./images/toyota.jpeg\" width=\"200\" height=\"200\" alt=\"\">\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3>Toyota</h3>\r\n");
      out.write("                <p>Genuine Parts for Optimal Performance of Your Toyota!</p>\r\n");
      out.write("                <div class=\"star\">\r\n");
      out.write("                  <i class=\"fa-solid fa-star checked\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star checked\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star checked\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star \"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star \"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\" style=\"margin-top: 30px;\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-4 py-3 py-md-0\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <img src=\"./images/hyhundai.jpeg\" width=\"200\" height=\"200\"alt=\"\">\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3>Hyhundai</h3>\r\n");
      out.write("                <p>Genuine Parts for Optimal Performance of Your Hyhundai!</p>\r\n");
      out.write("                <div class=\"star\">\r\n");
      out.write("                  <i class=\"fa-solid fa-star checked\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star checked\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star checked\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star \"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star \"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 py-3 py-md-0\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <img src=\"./images/tata.jpeg\" width=\"200\" height=\"200\" alt=\"\">\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3>Tata</h3>\r\n");
      out.write("                <p>Genuine Parts for Optimal Performance of Your Tata!</p>\r\n");
      out.write("                <div class=\"star\">\r\n");
      out.write("                  <i class=\"fa-solid fa-star checked\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star checked\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star checked\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star \"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star \"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 py-3 py-md-0\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <img src=\"./images/audi.jpeg\"width=\"200\" height=\"200\"  alt=\"\">\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3>Audi</h3>\r\n");
      out.write("                <p>Genuine Parts for Optimal Performance of Your Audi!</p>\r\n");
      out.write("                <div class=\"star\">\r\n");
      out.write("                  <i class=\"fa-solid fa-star checked\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star checked\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star checked\"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star \"></i>\r\n");
      out.write("                  <i class=\"fa-solid fa-star \"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Section Packages End -->\r\n");
      out.write("    <!-- Section Services Start -->\r\n");
      out.write("    <section class=\"services\" id=\"services\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"main-txt\">\r\n");
      out.write("          <h1><span>S</span>ervices</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\" style=\"margin-top: 30px;\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-4 py-3 py-md-0\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <i class =\"fa fa-book\"></i>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3>Spare Parts Catalog</h3>\r\n");
      out.write("                <p>Search by Vehicle: Allow users to search parts by entering their vehicle's make, model, and year.\r\n");
      out.write("                  Part Number Search: Provide a search function based on part numbers.\r\n");
      out.write("                  Category Browsing: Organize parts into categories (e.g., engine, brakes, transmission).\r\n");
      out.write("                  OEM vs. Aftermarket: Offer options for Original Equipment Manufacturer (OEM) parts and aftermarket alternatives.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 py-3 py-md-0\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <i class=\"fas fa-check-circle\"></i>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3> Compatibility Check</h3>\r\n");
      out.write("                <p>VIN Number Lookup: Allow users to enter their Vehicle Identification Number (VIN) to automatically find compatible parts.\r\n");
      out.write("                  Compatibility Verification: Automatically check and display compatibility of parts with different vehicle models.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 py-3 py-md-0\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <i class=\"fas fa-users\"></i>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3>Customer Support</h3>\r\n");
      out.write("                <p>Live Chat: Provide real-time customer support via live chat.\r\n");
      out.write("                  FAQs: Include a section with frequently asked questions and troubleshooting tips.\r\n");
      out.write("                  Return/Exchange Policy: Clearly outline return and exchange policies.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\" style=\"margin-top: 30px;\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-4 py-3 py-md-0\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <i class=\"fas fa-bell\"></i>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3>Subscription Services</h3>\r\n");
      out.write("                <p>Maintenance Subscription: Offer a subscription service for regular maintenance parts like oil filters and brake pads, delivered on a schedule.\r\n");
      out.write("                  Parts Alerts: Notify users when certain parts are back in stock or when there are new parts for their specific vehicle.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 py-3 py-md-0\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <i class=\"fas fa-download\"></i>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3>Installation Guides and Tutorials</h3>\r\n");
      out.write("                <p>How-To Videos: Offer video tutorials for part installation.\r\n");
      out.write("                  Downloadable Manuals: Provide PDF manuals for more detailed guidance.\r\n");
      out.write("                  Expert Tips: Include expert advice on maintaining and installing parts.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 py-3 py-md-0\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <i class=\"fas fa-mobile\"></i>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <h3>Mobile App</h3>\r\n");
      out.write("                <p>Mobile-Friendly Interface: Ensure the website is mobile-friendly or offer a dedicated app.\r\n");
      out.write("                  Push Notifications: Send alerts for deals, order updates, and new arrivals.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Section Services End -->\r\n");
      out.write("    <!-- Section Gallary Start -->\r\n");
      out.write("    <section class=\"gallary\" id=\"gallary\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"main-txt\">\r\n");
      out.write("          <h1><span>G</span>allary</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\" style=\"margin-top: 30px;\">\r\n");
      out.write("          <div class=\"col-md-4 py-3 py-md-0\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <img src=\"./images/lg1.jpeg\" alt=\"\" height=\"230px\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 py-3 py-md-0\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <img src=\"./images/g2.jpeg\" alt=\"\" height=\"230px\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 py-3 py-md-0\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <img src=\"./images/lg3.jpeg\" alt=\"\" height=\"230px\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\" style=\"margin-top: 30px;\">\r\n");
      out.write("          <div class=\"col-md-4 py-3 py-md-0\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <img src=\"./images/lg4.jpeg\" alt=\"\" height=\"230px\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 py-3 py-md-0\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <img src=\"./images/g5.jpeg\" alt=\"\" height=\"230px\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 py-3 py-md-0\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <img src=\"./images/g6.jpeg\" alt=\"\" height=\"230px\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Section Gallary End -->\r\n");
      out.write("    <!-- About Start -->\r\n");
      out.write("    <section class=\"about\" id=\"about\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"main-txt\">\r\n");
      out.write("          <h1>About <span>Us</span></h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\" style=\"margin-top: 50px;\">\r\n");
      out.write("          <div class=\"col-md-6 py-3 py-md-0\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <img src=\"./images/about.jpeg\" height=\"500px\" width=\"400px\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6 py-3 py-md-0\">\r\n");
      out.write("            <h2>Your Trusted Automotive Partner</h2>\r\n");
      out.write("            <p>Welcome to Parts Universe, your trusted partner in keeping your vehicle running smoothly and efficiently. Established in 2002, our mission has always been simple: to provide high-quality, reliable spare parts for all types of vehicles at competitive prices, backed by exceptional customer service.</p>\r\n");
      out.write("            <a href=\"aboutus.jsp\" class=\"btn btn-primary\">Read More...</a>\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- About End -->\r\n");
      out.write("    <!-- Footer Start -->\r\n");
      out.write("    <footer id=\"footer\">\r\n");
      out.write("      <h1><span>Parts</span>Universe</h1>\r\n");
      out.write("      <p>Maximize Your Vehicle's Potential with Our High-Quality Replacement Parts!</p>\r\n");
      out.write("      <div class=\"social-links\">\r\n");
      out.write("        <i class=\"fa-brands fa-twitter\"></i>\r\n");
      out.write("        <i class=\"fa-brands fa-facebook\"></i>\r\n");
      out.write("        <i class=\"fa-brands fa-instagram\"></i>\r\n");
      out.write("        <i class=\"fa-brands fa-youtube\"></i>\r\n");
      out.write("        <i class=\"fa-brands fa-pinterest-p\"></i>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"credit\">\r\n");
      out.write("        <p>Designed By <a href=\"#\">SLIIT Students</a></p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"copyright\">\r\n");
      out.write("        <p>&copy;Copyright SLIIT Students. All Rights Reserved</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- Footer End -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"script/index.js\"></script> \r\n");
      out.write("    <script>\r\n");
      out.write("    function performSearch() {\r\n");
      out.write("        const query = document.getElementById('query').value.toLowerCase().trim();\r\n");
      out.write("\r\n");
      out.write("        // Corrected mapping between search terms and URLs\r\n");
      out.write("        const pages = {\r\n");
      out.write("            'login': 'login.jsp',\r\n");
      out.write("            'signup': 'sinup.jsp', // Make sure this is correctly spelled\r\n");
      out.write("            'about': 'about.jsp',\r\n");
      out.write("            'faq': 'faq.jsp',\r\n");
      out.write("            'home': 'index.jsp',\r\n");
      out.write("            'profile': 'useraccount.jsp',\r\n");
      out.write("            'contact': 'contactus.jsp',\r\n");
      out.write("            't&c': 't&c.jsp',\r\n");
      out.write("            // Add more pages as needed\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        // Attempt to match the query to a page\r\n");
      out.write("        if (pages[query]) {\r\n");
      out.write("            window.location.href = pages[query];\r\n");
      out.write("        } else {\r\n");
      out.write("            alert(\"Page not found. Please try another search term.\");\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        return false; // Prevent the form from submitting and reloading the page\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
